spring.application.name: resource
server.port: 18081

security.oauth2.resource.token-info-uri: http://localhost:9999/uaa/oauth/check_token
security.oauth2.client.client-id: demo
security.oauth2.client.client-secret: demo

spring.jackson.date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
